spring.application.name: credentials
spring.mvc.throw-exception-if-no-handler-found: true
spring.web.resources.add-mappings: false
server.port: 9001
spring.datasource:
  url: jdbc:mysql://localhost:3307/credential-storage?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
  username: root
  password: 123456

## Hibernate properties
spring.jpa.hibernate.ddl-auto: update
spring.jpa.open-in-view: false
spring.datasource.hikari.initializationFailTimeout: 60000

security.jwt:
  secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  # 1h in seconds
  expiration-time: 3600

---
spring.config.activate.on-profile: qa
server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/credential-storage

security.jwt:
  secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  # 1h in seconds
  expiration-time: 120
---
spring.config.activate.on-profile: prod
server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/credential-storage

security.jwt:
  secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  # 1h in seconds
  expiration-time: 240
